### PR TITLE
COMPAT: create bucket with empty name

### LINKED ISSUE #298: COMPAT: create bucket with empty name: errors incompatible with AWS
When creating bucket with empty name: should return `405 MethodNotAllowed`

On **ceph/s3-tests**, these changes fix:
`ERROR: s3tests.functional.test_s3.test_bucket_create_naming_bad_short_empty`

### PR DESCRIPTION
**Pull request by nicolas2bert**
FIXES #298

### CODE REVIEW

File: lib/api/apiUtils/bucket/bucketCreation.js [hunk 1]
```diff
@@ -136,7 +136,10 @@ export function cleanUpBucket(bucketMD, canonicalID, log, callback) {
 export function createBucket(authInfo, bucketName, headers,
     locationConstraint, log, cb) {
     log.trace('Creating bucket');
-    assert.strictEqual(typeof bucketName, 'string');
+    if (typeof bucketName !== 'string') {
```
Comment (rahulreddy) [inline lib/api/apiUtils/bucket/bucketCreation.js]: That assertion was for type assertions of function parameters (I was not a fan of that). Anyways, shouldn't you be checking `if(bucketName === '')`?

Comment (nicolas2bert) [inline lib/api/apiUtils/bucket/bucketCreation.js]: If bucketName is empty (not undefined) it will jumb here: https://github.com/scality/S3/blob/b246509b83f45529131f3abbc1b961ec85feb123/lib/routes.js#L91

**Comment by nicolas2bert** [comment]
Thanks @rahulreddy, I also had to check that the request was not` listBuckets` because this one is the only one which allows undefined bucketName.

**Comment by nicolas2bert** [comment]
@ironman-machine please

**Comment by LaurenSpiegel** [comment]
end to end passed here: http://ci.ironmann.io/gh/scality/Integration/5821
