### PR TITLE
FIX: Refactor objectPutPart API

### LINKED ISSUE #153: Refactor objectPutPart API
Metadata is being called twice to get the MPU shadow bucket metadata (once to get the MPU bucket metadata with "services.getMPUBucket" and then again when validating authorization with "services.metadataValidateMultipart").

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Fixes refactoring part of #153

* Call `metadata.getBucket` directly and perform validation checks in the API.
* Remove calls to `services.metadataValidateAuthorization`, `services.metadataValidateMultipart`, and `services.getMPUBucket`.
* Remove `doStore` function and instead call `services.dataStore` and `services.metadataStorePart` directly in API.
* Remove extraneous code after the above changes.

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by rahulreddy** [comment]
Looks like you committed dump.rdb file by mistake. Can you remove it?

**Comment by bennettbuchanan** [comment]
Thanks @rahulreddy! I've removed it.

File: lib/api/apiUtils/authorization/aclChecks.js [hunk 1]
```diff
@@ -114,3 +114,43 @@ export function isObjAuthorized(bucket, objectMD, requestType, canonicalID) {
     }
     return false;
 }
+
+export function isMpuAuthorized(mpuBucket, authInfo, response, requestType) {
```
Comment (LaurenSpiegel) [inline lib/api/apiUtils/authorization/aclChecks.js]: please add jsdoc for this function.  also, please use something clearer than "response" for the argument name here.  Maybe 'mpuOverviewObj'.

File: lib/api/objectPutPart.js [hunk 2]
```diff
@@ -72,95 +36,165 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
+    const uploadId = request.query.uploadId;
+    const mpuBucketName = `${constants.mpuBucketPrefix}${bucketName}`;
+
+    // If bucket has no server-side encryption, `cipherBundle` remains `null`.
+    let cipherBundle = null;
+    let splitter = constants.splitter;
+
+    return async.waterfall([
+        // Get the bucket.
+        next => metadata.getBucket(bucketName, log, next),
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: I'd prefer going a little longer form here so we can log here if there is an error getting the bucket.

File: lib/api/objectPutPart.js [hunk 3]
```diff
@@ -72,95 +36,165 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
+    // `request.query.uploadId` must be called with that exact capitalization.
+    const uploadId = request.query.uploadId;
+    const mpuBucketName = `${constants.mpuBucketPrefix}${bucketName}`;
+
+    // If bucket has no server-side encryption, `cipherBundle` remains `null`.
+    let cipherBundle = null;
+    let splitter = constants.splitter;
+
+    return async.waterfall([
+        // Get the bucket.
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: // Get the destination bucket

File: lib/api/objectPutPart.js [hunk 4]
```diff
@@ -72,95 +36,165 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
+
+            return next(null, bucket);
+        },
+        // Get bucket server-side encryption, if it exists.
+        (bucket, next) => {
+            const encryption = bucket.getServerSideEncryption();
+
+            if (encryption) {
+                return kms.createCipherBundle(encryption, log, (err, res) => {
+                    cipherBundle = res;
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: log any error here

File: lib/api/objectPutPart.js [hunk 5]
```diff
@@ -72,95 +36,165 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
                 });
-        });
+            }
+
+            return next();
+        },
+        // Get the MPU shadow bucket.
+        next => metadata.getBucket(mpuBucketName, log, (err, mpuBucket) => {
+            if (err) {
+                return next(errors.NoSuchUpload);
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: log error and make clear this is an error from getting the shadow mpu bucket

File: lib/api/objectPutPart.js [hunk 6]
```diff
@@ -72,95 +36,165 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
+            return next(null, mpuBucket);
+        }),
+        // Check authorization of the MPU shadow bucket.
+        (mpuBucket, next) => {
+            // BACKWARD: Remove to remove the old splitter
+            if (mpuBucket.getMdBucketModelVersion() < 2) {
+                splitter = constants.oldSplitter;
+            }
+
+            const args = {
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: Instead of doing a listing, I think we can do a straight get object from metadata, can't we?  At some point we had more info in the key so we weren't able to do that but I think it's possible now and would be more straightforward than doing a listing to get one key.

File: lib/api/objectPutPart.js [hunk 7]
```diff
@@ -72,95 +36,165 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
+                bucketName,
+                owner: canonicalID,
+                namespace: request.namespace,
+            };
+
+            return services.dataStore(null, objectKeyContext, cipherBundle,
+                request, size, streamingV4Params, log, next);
+        },
+        // Store data locations in metadata.
+        (pass, dataGetInfo, hexDigest, next) => {
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: pass?

File: lib/services.js [hunk 8]
```diff
@@ -554,14 +554,19 @@ export default {
                         return cb(errors.NoSuchUpload);
                     }
 
+                    if (!isMpuAuthorized(mpuBucket, authInfo, response,
```
Comment (LaurenSpiegel) [inline lib/services.js]: where is this whole function (metadtataValidateMultipart) still used?  Is it possible to still use this function in put part so we don't have duplication if this is still being used or should we get rid of this altogether?

Comment (rahulreddy) [inline lib/services.js]: I originally extracted this method with the intention of using it. It was going to be a step in a direction to dismantle `services.metadataValidateMultipart`. I like the step @bennettbuchanan took to bring the validation logic directly into the api.

@bennettbuchanan you can remove this change, we will make changes similar to what you did for other apis which are using validatemultipart method as a different PR.

Comment (bennettbuchanan) [inline lib/services.js]: Okay, thanks @rahulreddy

File: lib/api/objectPutPart.js [hunk 9]
```diff
@@ -87,80 +56,146 @@ export default function objectPutPart(authInfo, request, streamingV4Params,
...
+                dataGetInfoArr[0].sseCipheredDataKey = cipheredDataKey;
+            }
+            const mdParams = {
+                partNumber: _getPaddedPartNumber(partNumber),
+                contentMD5: hexDigest,
+                size,
+                uploadId,
+                splitter,
+            };
+            return services.metadataStorePart(mpuBucketName, dataGetInfoArr,
```
Comment (rahulreddy) [inline lib/api/objectPutPart.js]: This can be extracted into this api as well. It doesn't carry any extra setup, so it should be ok.

File: lib/api/objectPutPart.js [hunk 10]
```diff
@@ -87,80 +56,146 @@ export default function objectPutPart(authInfo, request, streamingV4Params,
...
-        });
+        },
+        // Store in data backend.
+        next => {
+            const objectKeyContext = {
+                bucketName,
+                owner: canonicalID,
+                namespace: request.namespace,
+            };
+            return services.dataStore(null, objectKeyContext, cipherBundle,
```
Comment (rahulreddy) [inline lib/api/objectPutPart.js]: After `services.metadataStorePart` this would be the last services call left in this api. My recommendation is to move it to apiUtils/object. Then we could introduce a refactor for other apis to follow the suit.

File: lib/api/objectPutPart.js [hunk 11]
```diff
@@ -87,80 +60,158 @@ export default function objectPutPart(authInfo, request, streamingV4Params,
...
+    const mpuBucketName = `${constants.mpuBucketPrefix}${bucketName}`;
+    const objectKey = request.objectKey;
+    // If bucket has no server-side encryption, `cipherBundle` remains `null`.
+    let cipherBundle = null;
+    let splitter = constants.splitter;
+    return async.waterfall([
+        // Get the destination bucket.
+        next => metadata.getBucket(bucketName, log, (err, bucket) => {
+            if (err && err.NoSuchBucket) {
+                return next(errors.NoSuchUpload);
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: Did you test this with AWS?  If there is no bucket and you try to do an upload it responds with NoSuchUpload?

File: lib/api/apiUtils/object/storeObject.js [hunk 12]
```diff
@@ -0,0 +1,81 @@
+import { errors } from 'arsenal';
```
Comment (LaurenSpiegel) [inline lib/api/apiUtils/object/storeObject.js]: this is all just moved from services with the functions there remaining?  will you please add a note in services.js that these are to be deleted once references are updated in the other api's and open an issue for that to be done?

File: lib/api/objectPutPart.js [hunk 13]
```diff
@@ -1,57 +1,24 @@
...
-                        return cb(null, calculatedHash);
-                    });
-            });
-    };
+// We pad the partNumbers so that the parts will be sorted in numerical order.
+function _getPaddedPartNumber(number) {
+    return `000000${number}`.substr(-5);
+}
+
+function _getPrefixKey(splitter, objectKey, uploadId) {
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: I would call this _getOverviewKey

**Comment by LaurenSpiegel** [comment]
So much clearer.  Just a few remaining questions/comments.  thanks!!

File: lib/api/objectPutPart.js (hunk 13 above)
Comment (bennettbuchanan) [inline lib/api/objectPutPart.js]: Updated.

File: lib/api/apiUtils/object/storeObject.js (hunk 12 above)
Comment (bennettbuchanan) [inline lib/api/apiUtils/object/storeObject.js]: I have added a TODO comment in services.js.

File: lib/api/objectPutPart.js (hunk 11 above)
Comment (bennettbuchanan) [inline lib/api/objectPutPart.js]: Thanks, good catch! I have updated this to return a `NoSuchBucket` error as is the expected behavior. A `NoSuchUpload` error in this API should only be returned when the MPU bucket is not found.

File: lib/api/objectPutPart.js [hunk 14]
```diff
@@ -72,13 +39,19 @@ function doStore(objectKeyContext, cipherBundle, request, log,
...
     log.debug('processing request', { method: 'objectPutPart' });
-
-    const bucketName = request.bucketName;
-    const objectKey = request.objectKey;
     const size = request.parsedContentLength;
+    // If part size is greater than 5GB, reject it.
+    // Note: Parts are supposed to be at least 5MB except for last part.
+    // However, there is no way to know whether a part is the last part since
+    // keep taking parts until get a completion request.  But can expect parts
+    // of at least 5MB until last part.  Also, we check that part sizes are
```
Comment (nicolas2bert) [inline lib/api/objectPutPart.js]: Can you please reword it ? :)

Comment (bennettbuchanan) [inline lib/api/objectPutPart.js]: Thanks for pointing this out. I think I have made it more clear.

File: lib/api/apiUtils/object/storeObject.js (hunk 12 above)
Comment (rahulreddy) [inline lib/api/apiUtils/object/storeObject.js]: I think it has to be it's own PR for separation of concerns.

Comment (LaurenSpiegel) [inline lib/api/apiUtils/object/storeObject.js]: Please go ahead and squash, rebase and run an end to end and we can merge this then you can open the other pr.

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by bennettbuchanan** [comment]
@ironman-machine after `log.trace` object deletion

**Comment by bennettbuchanan** [comment]
@ironman-machine with POC

**Comment by bennettbuchanan** [comment]
@ironman-machine 
CI_AGGRESSOR_FORCE_BUILD=true

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by bennettbuchanan** [comment]
@ironman-machine hey Jarvis

**Comment by bennettbuchanan** [comment]
end-to-end passed with a variable declaration change in storeObject.js. The `dataStore` function has been refactored accordingly and a new function `checkHashMatchMD5` added.

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by bennettbuchanan** [comment]
end-to-end rebuilt and passed here:
http://ci.ironmann.io/gh/scality/Integration/7246

**Comment by bennettbuchanan** [comment]
@ironman-machine

**Comment by DavidPineauScality** [comment]
@ironman-machine sorry, ultron/rel/6.3 branch wasnt created on Integration. Should be better now.

**Comment by bennettbuchanan** [comment]
Hi @DavidPineauScality, thanks for checking this. 😸

**Comment by bennettbuchanan** [comment]
@ironman-machine after latest rebase

**Comment by bennettbuchanan** [comment]
@ironman-machine after rebase onto master
