### PR TITLE
fix: error response for object level encryption

### LINKED ISSUE #165: Should return error when encryption header sent on request (other than bucket level encryption)
We don't currently support object level encryption so an error should be returned if these headers are sent.

### PR DESCRIPTION
**Pull request by rahulreddy**
fix #165

### CODE REVIEW

File: lib/routes/routePUT.js [hunk 1]
```diff
@@ -122,6 +122,21 @@ export default function routePUT(request, response, log, utapi) {
             log.end().addDefaultFields({
                 contentLength: request.headers['content-length'],
             });
+
+            // object level encryption
+            const encryptHeaders = [
```
Comment (LaurenSpiegel) [inline lib/routes/routePUT.js]: maybe move this to constants or at least outside of the actual route function.

File: lib/routes/routePUT.js [hunk 2]
```diff
@@ -122,6 +122,21 @@ export default function routePUT(request, response, log, utapi) {
...
+                'x-amz-server-side-encryption',
+                'x-amz-server-side-encryption-customer-algorithm',
+                'x-amz-server-side-encryption-aws-kms-key-id',
+                'x-amz-server-side-encryption-context',
+                'x-amz-server-side-encryption-customer-key',
+                'x-amz-server-side-encryption-customer-key-md5',
+            ];
+            if (encryptHeaders.some(i => request.headers[i] !== undefined)) {
```
Comment (LaurenSpiegel) [inline lib/routes/routePUT.js]: move this to top of else to put part and object copy are impacted as well

Comment (rahulreddy) [inline lib/routes/routePUT.js]: I moved it to the top so that put part and object copy get the benefit as well.

File: lib/routes/routePUT.js (hunk 1 above)
Comment (rahulreddy) [inline lib/routes/routePUT.js]: moved it outside of routes function.

**Comment by rahulreddy** [comment]
Added a commit which
 - skips copyObject test which uses encryption option
 - adds a test for object put part

**Comment by nicolas2bert** [comment]
👍

**Comment by LaurenSpiegel** [comment]
@ironman-machine check it

**Comment by LaurenSpiegel** [comment]
@ironman-machine taking a break?

**Comment by LaurenSpiegel** [comment]
@ironman-machine revived?

**Comment by LaurenSpiegel** [comment]
@ironman-machine ready to play nicely now?

**Comment by LaurenSpiegel** [comment]
@ironman-machine get it on

**Comment by rahulreddy** [comment]
@ironman-machine again
