### PR TITLE
COMPAT:listing objects with percentage delimiter

### LINKED ISSUE #294: COMPAT: when listing objects with percentage delimiter characters : FAILS
When listing objects with percentage delimiter characters: request fails.
On **ceph/s3-tests**, this test fails:
- `ERROR: s3tests.functional.test_s3.test_bucket_list_delimiter_percentage`

### PR DESCRIPTION
**Pull request by nicolas2bert**
FIXES #294 

Keys and values are already decoded with .query
https://nodejs.org/api/url.html#url_urlobject_query

### CODE REVIEW

File: tests/functional/aws-node-sdk/test/bucket/get.js [hunk 1]
```diff
@@ -134,6 +134,24 @@ describe('GET Bucket - AWS.S3.listObjects', () => {
...
+                { Bucket, Key: 'testB%test.json', Body: '{}' },
+                { Bucket, Key: 'testA%' },
+                { Bucket, Key: 'testA%test.json', Body: '{}' },
+                { Bucket, Key: 'testA%test%test.json', Body: '{}' },
+            ];
+
+            Promise
+                .mapSeries(objects, param => s3.putObjectAsync(param))
+                .then(() => s3.listObjectsAsync({ Bucket, Delimiter: '%' }))
+                .then(() => done())
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/test/bucket/get.js]: Shouldn't you be checking that the result matches what you expect?  Also, please return the promise and you don't need to use "done" with promises.

**Comment by nicolas2bert** [comment]
@ironman-machine thanks
