### PR TITLE
COMPAT: websiteGet and websiteHead with ACLs

### LINKED ISSUE #573: COMPAT: websiteGet with object ACL do not return correct errors
**websiteGet:**
- If bucket is private and no index object: should return 403 error status.
- If bucket is public and no index object: should return 404 error status.

- If index object private and error object private: return 403 error status.

This change fixes:

- `FAIL: s3tests.functional.test_s3_website.test_website_public_bucket_list_empty`
- `FAIL: s3tests.functional.test_s3_website.test_website_public_bucket_list_empty_missingerrordoc`
- `FAIL: s3tests.functional.test_s3_website.test_website_private_bucket_list_empty_blockederrordoc`
- `FAIL: s3tests.functional.test_s3_website.test_website_public_bucket_list_empty_blockederrordoc`
- `FAIL: s3tests.functional.test_s3_website.test_website_public_bucket_list_private_index_blockederrordoc`
- ` FAIL: s3tests.functional.test_s3_website.test_website_public_bucket_list_empty_gooderrordoc`

### PR DESCRIPTION
**Pull request by nicolas2bert**
FIXES #573

### CODE REVIEW

File: lib/api/api.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ auth.setHandler(vault);
 const api = {
     callApiMethod(apiMethod, request, log, callback, locationConstraint) {
         // no need to check auth on website or cors preflight requests
-        if (apiMethod === 'websiteGet' || apiMethod === 'websiteHead' ||
+        if (apiMethod === 'websiteHead' ||
```
Comment (electrachong) [inline lib/api/api.js]: unfortunately you might be able to expect most of the changes you made to also apply to websiteHead, and it could be a little strange to have different behavior between websiteHead/Get. are you planning to refactor wesiteHead in separate PR or commit?

File: tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+    // CEPH: test_website_public_bucket_list_private_index_blockederrordoc
+    {
+        it: 'should return 403 if public bucket - private index - public ' +
+        'error documents',
+        bucketACL: 'public',
+        objects: { index: 'private', error: 'private' },
+        html: '403-access-denied',
+    },
+    {
+        it: 'should return index doc if private bucket - private index - ' +
```
Comment (electrachong) [inline tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js]: is this true? seems a bit strange to me, does it make sense to you?

Comment (nicolas2bert) [inline tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js]: Yes - seems that a **public** object can be reached even though his bucket is private.
Tested against AWS.

Comment (electrachong) [inline tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js]: ah OK, the it statement will be changed to `public index` then right? :)

Comment (nicolas2bert) [inline tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js]: ho yes, my description is not correct - thanks :)

File: lib/api/api.js (hunk 1 above)
Comment (nicolas2bert) [inline lib/api/api.js]: Thanks for your review @electrachong - I modified websiteHead + tests,  so it is compatible as well.

File: lib/api/api.js [hunk 3]
```diff
@@ -44,8 +44,7 @@ auth.setHandler(vault);
 const api = {
     callApiMethod(apiMethod, request, log, callback, locationConstraint) {
         // no need to check auth on website or cors preflight requests
```
Comment (LaurenSpiegel) [inline lib/api/api.js]: update comment

File: lib/api/websiteGet.js [hunk 4]
```diff
@@ -12,13 +12,14 @@ import { isObjAuthorized } from './apiUtils/authorization/aclChecks';
...
 import { pushMetric } from '../utapi/utilities';
+import { isBucketAuthorized } from './apiUtils/authorization/aclChecks';
 
 /**
  * _errorActions - take a number of actions once have error getting obj
  * @param {object} err - arsenal errors object
  * @param {string} errorDocument - key to get error document
  * @param {object []} routingRules - array of routingRule objects
- * @param {string} bucketName - bucket name from request
+ * @param {string} bucket - bucket from request
```
Comment (LaurenSpiegel) [inline lib/api/websiteGet.js]: this is an object, not a string, correct?
I would describe it as the bucket metadata, not bucket from request.

File: lib/api/websiteGet.js [hunk 5]
```diff
@@ -44,6 +46,12 @@ function _errorActions(err, errorDocument, routingRules,
                     // to true
                     return callback(err, true, null, corsHeaders);
                 }
+                // do not return the error object if it is private
```
Comment (LaurenSpiegel) [inline lib/api/websiteGet.js]: is the idea that you just return the default error message if the object is private rather than sending a stored error file?  please clarify

File: lib/api/api.js (hunk 3 above)
Comment (nicolas2bert) [inline lib/api/api.js]: done

**Comment by nicolas2bert** [comment]
http://ci.ironmann.io/gh/scality/Integration/9459

**Comment by nicolas2bert** [comment]
E2E- http://ci.ironmann.io/gh/scality/Integration/9468

**Comment by nicolas2bert** [comment]
New E2E - http://ci.ironmann.io/gh/scality/Integration/9472

**Comment by nicolas2bert** [comment]
Rebuild: http://ci.ironmann.io/gh/scality/Integration/9482

**Comment by nicolas2bert** [comment]
New E2E: http://ci.ironmann.io/gh/scality/Integration/9484

**Comment by nicolas2bert** [comment]
New New New E2E: http://ci.ironmann.io/gh/scality/Integration/9499
Should pass after https://github.com/scality/S3/pull/605 has been merged.
