### PR TITLE
COMPAT: putObjectACL reject changing owner ID

### LINKED ISSUE #367: COMPAT: AWS rejects overwriting Owner ID for objectPutACL
Should return `AccessDenied` if attempting to put object acl that changes the owner ID of the resource.

On **ceph/s3-tests**, this test fails:
* `FAIL: s3tests.functional.test_s3.test_object_giveaway`

### PR DESCRIPTION
**Pull request by electrachong**
FIXES #367

Hope it's OK I added onto aclUtils.parseAclXml! Open to other suggestions.

### CODE REVIEW

**Comment by electrachong** [comment]
@ironman-machine

File: lib/utilities/aclUtils.js [hunk 1]
```diff
@@ -114,7 +114,17 @@ aclUtils.parseAclXml = function parseAclXml(toBeParsed, log, next) {
         const jsonGrants = result
             .AccessControlPolicy.AccessControlList[0].Grant;
         log.trace('acl grants', { aclGrants: jsonGrants });
-        return next(null, jsonGrants);
+
+        if (!result.AccessControlPolicy.Owner
+            || result.AccessControlPolicy.Owner.length === 0
+            || result.AccessControlPolicy.Owner[0] === ''
+            || result.AccessControlPolicy.Owner[0].ID.length !== 1
```
Comment (alexandre-merle) [inline lib/utilities/aclUtils.js]: if Owner[0] is a string different from empty string, the worker will crash here :)

File: lib/utilities/aclUtils.js [hunk 2]
```diff
@@ -114,7 +114,17 @@ aclUtils.parseAclXml = function parseAclXml(toBeParsed, log, next) {
         const jsonGrants = result
             .AccessControlPolicy.AccessControlList[0].Grant;
         log.trace('acl grants', { aclGrants: jsonGrants });
-        return next(null, jsonGrants);
+
+        if (!result.AccessControlPolicy.Owner
+            || result.AccessControlPolicy.Owner.length === 0
```
Comment (electrachong) [inline lib/utilities/aclUtils.js]: yeah I think you're right, I updated according to your suggestion

File: lib/utilities/aclUtils.js [hunk 3]
```diff
@@ -117,7 +117,7 @@ aclUtils.parseAclXml = function parseAclXml(toBeParsed, log, next) {
 
         if (!result.AccessControlPolicy.Owner
```
Comment (rahulreddy) [inline lib/utilities/aclUtils.js]: This is a bit out of scope but since we are touching the property, do you mind changing this to
```js
Array.isArray(result.AccessControlPolicy.Owner)
```
This way it's guaranteed that result.AccessControlPolicy.Owner is an array with at least one element in it per the conditions.

Comment (electrachong) [inline lib/utilities/aclUtils.js]: does this make more sense? @rahulreddy @alexandre-merle 
https://github.com/scality/S3/pull/379/commits/12dfa4133253f334e0f2e3cef3ff4c1834cfea15

Comment (alexandre-merle) [inline lib/utilities/aclUtils.js]: yes, its good :)

Comment (rahulreddy) [inline lib/utilities/aclUtils.js]: Thanks, looks good to me.

Comment (electrachong) [inline lib/utilities/aclUtils.js]: what about result.AccessControlPolicy.Owner[0].ID[0], do we need to check it is typeof 'string' and not just another object or array?

**Comment by electrachong** [comment]
did a bit of refactoring at @rahulreddy's request, will check with ironman machine once it seems like circle ci issues are resolved

**Comment by electrachong** [comment]
@ironman-machine try puppy

**Comment by electrachong** [comment]
end-to-end passed

File: lib/api/objectPutACL.js [hunk 4]
```diff
@@ -119,6 +120,16 @@ export default function objectPutACL(authInfo, request, log, cb) {
             let usersIdentifiedByEmail = [];
             let usersIdentifiedByGroup = [];
             let usersIdentifiedByID = [];
+
+            // If grants set by xml and owner ID is incorrectly overwritten
```
Comment (LaurenSpiegel) [inline lib/api/objectPutACL.js]: what do you mean by overwritten?  do you just mean they got the owner id wrong?  If so, please state that.

File: tests/functional/aws-node-sdk/test/object/putObjAcl.js [hunk 5]
```diff
@@ -62,5 +95,29 @@ describe('PUT Object ACL', () => {
...
+                const putAclParams = {
+                    Bucket: bucketName,
+                    Key,
+                    AccessControlPolicy: acp,
+                };
+                s3.putObjectAcl(putAclParams, err => {
+                    assert(err);
+                    // Note the supplied canonical ID is not associated with
+                    // a real AWS account, so AWS will raise a 400 -
+                    // InvalidArgument instead if running w. AWS_ON_AIR=true
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/test/object/putObjAcl.js]: we should do itSkipAWS on this test then.  see some samples on how to do that.

File: tests/unit/api/objectPutACL.js [hunk 6]
```diff
@@ -151,14 +158,9 @@ describe('putObjectACL API', () => {
...
-                'x-amz-grant-read':
-                    `uri=${constants.logId}`,
-                'x-amz-grant-read-acp':
-                    'id="79a59df900b949e55d96a1e698fbacedfd6e09d98eac' +
-                    'f8f8d5218e7cd47ef2be"',
-                'x-amz-grant-write-acp':
-                    'id="79a59df900b949e55d96a1e698fbacedfd6e09d98eac' +
-                    'f8f8d5218e7cd47ef2bf"',
+                'x-amz-grant-read': `uri=${constants.logId}`,
+                'x-amz-grant-read-acp': `id="${ownerID}"`,
```
Comment (LaurenSpiegel) [inline tests/unit/api/objectPutACL.js]: why quotes around the id?  I've been fixing that in another pr.  I don't see why we did this originally.

File: tests/unit/helpers.js [hunk 7]
```diff
@@ -133,3 +133,56 @@ export class DummyRequestLogger {
         return this;
     }
 }
+
+export class AccessControlPolicy {
```
Comment (LaurenSpiegel) [inline tests/unit/helpers.js]: cool helper function

File: lib/api/objectPutACL.js (hunk 4 above)
Comment (electrachong) [inline lib/api/objectPutACL.js]: changed it

File: tests/functional/aws-node-sdk/test/object/putObjAcl.js (hunk 5 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/test/object/putObjAcl.js]: :thumbsup:
