### PR TITLE
FIX: remove auth credential check from websiteHead/Get

### LINKED ISSUE #553: COMPAT: should not check vault credentials for get/head website requests
UPDATE: @nicolas2bert fixed the following behavior in https://github.com/scality/S3/issues/573 but we realized his refactor involved checking auth credentials, when we have not tested AWS behavior for website endpoint requests with credentials. Testing reveals we should not be making checking authentication credential and should only check if objects and buckets have public-* acls.

-----------------------------------------------

While testing cors headers responses for website endpoints, I found AWS responds with the following to requests for an object that does not exist (on bucket with public-read-write ACLs).

```
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: test</li>
<li>RequestId: BC20E1D1388DFB25</li>
<li>HostId: NX+GRaKR27CCl/kiMa4iiF/KDApIrzT299WVHVgEhuG8o2X94FIfE6R/C+MFYSpiFvZRiufWxf8=</li>
</ul>
<hr/>
</body>
</html>
```

S3 current response:
```
<html><head><title>403 Forbidden</title></head><body><h1>403 Forbidden</h1><ul><li id='code'>Code: AccessDenied</li><li id='message'>Message: Access Denied</li><li>BucketName: bucketwebsitetester</li><li>RequestId: 8d95b84118e1695f47aa</li></ul><hr></body></html>
```

I remember we believed this was the appropriate response when testing/developing the website endpoint responses before, so will want to investigate the reason for that belief and if we have any other tests to corroborate a 403 AccessDenied response in certain scenarios (e.g. different ACLs).

### PR DESCRIPTION
**Pull request by electrachong**
FIXES #553

Also includes commit for refactoring website tests and clean-up in preparation for adding auth credentials to the website test requests. Zombie was a neat tool for visiting websites as if in a browser, but since it added unnecessary wait time to the redirect tests and we can check what we need in the response using the node `http`/`https` request module, I removed it.

### CODE REVIEW

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 1]
```diff
@@ -1,6 +1,206 @@
...
+            'website configuration',
+            `BucketName: ${bucketName}`,
+        ]);
+    } else if (type === '404-not-found') {
+        _assertResponseHtml(response.body, 'ul', [
+            'Code: NoSuchKey',
+            'Message: The specified key does not exist.',
+        ]);
+    } else {
+        throw new Error('This 404 error is not checked in ' +
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: would it be accurate to say 'This 404 error is not a recognized 404 error in the checkHTML function.'?

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 2]
```diff
@@ -1,6 +1,206 @@
...
+
+function _assertResponseHtml404(method, response, type, bucketName) {
+    assert.strictEqual(response.statusCode, 404);
+    if (method === 'HEAD') {
+        if (type !== '404-no-such-bucket'
+        && type !== '404-no-such-website-configuration'
+        && type !== '404-not-found') {
+            throw new Error('This 404 error is not checked in ' +
+            'checkHTML()');
+        }
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: assert the error response headers

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 3]
```diff
@@ -1,6 +1,206 @@
...
+        _assertResponseHtml(response.body, 'h1', '403 Forbidden');
+        _assertResponseHtml(response.body, 'ul', [
+            'Code: AccessDenied',
+            'Message: Access Denied',
+        ]);
+        if (type === '403-retrieve-error-document') {
+            _assertResponseHtml(response.body, 'h3',
+            'An Error Occurred While Attempting to ' +
+            'Retrieve a Custom Error Document');
+            const startIndex = response.body.indexOf('</h3>') + 5;
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: why the closing header tag plus 5?

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 4]
```diff
@@ -36,91 +236,61 @@ export class WebsiteConfigTester {
...
-                    'Message: The specified bucket does not have a website ' +
-                    'configuration');
-                    browser.assert.text('ul:first-of-type > li:nth-child(3)',
-                    `BucketName: ${bucketName}`);
-                } else if (type === '404-not-found') {
-                    browser.assert.text('ul:first-of-type > li:first-child',
-                    'Code: NoSuchKey');
-                    browser.assert.text('ul:first-of-type > li:nth-child(2)',
-                    'Message: The specified key does not exist.');
+    static checkHTML(auth, method, url, type, redirectUrl, bucketName,
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: please add a jsdoc for this (especially to explain what type is)

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 5]
```diff
@@ -36,91 +236,61 @@ export class WebsiteConfigTester {
...
+                        return this.checkHTML(null, method,
+                        res.headers.location, 'redirected-user', null, null,
+                        callback);
+                    }
+                } else if (type === 'index-user') {
+                    _assertResponseHtmlIndexUser(res);
                 } else {
-                    throw new Error('This 404 error is not checked in ' +
-                    'checkHTML()');
+                    throw new Error('This is not checked in checkHTML()');
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: This type is not recognized by the checkHTML function

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 6]
```diff
@@ -36,91 +236,61 @@ export class WebsiteConfigTester {
...
+     * @param {function} cb - callback to end test
+     * @return {undefined}
+     */
+    static makeHeadRequest(auth, url, expectedStatusCode, expectedHeaders, cb) {
+        _makeWebsiteRequest(auth, 'HEAD', url, (err, res) => {
+            // body should be empty
+            assert.deepStrictEqual(res.body, '');
+            assert.strictEqual(res.statusCode, expectedStatusCode);
+            const headers = Object.keys(expectedHeaders);
+            for (let i = 0; i < headers.length; i++) {
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: are we guaranteed that the headers are always returned in the same order?

File: tests/functional/aws-node-sdk/test/object/websiteGet.js [hunk 7]
```diff
@@ -504,20 +419,17 @@ describe('User visits bucket website endpoint', () => {
                 };
                 const redirect = {
                     HostName: 'www.google.com',
-                    ReplaceKeyPrefixWith: '/about',
+                    ReplaceKeyPrefixWith: 'about/',
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/test/object/websiteGet.js]: is this change aws compatible?

File: tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js [hunk 8]
```diff
@@ -132,14 +129,30 @@ describe('User visits bucket website endpoint with ACL', () => {
...
+                            // Give some time for AWS to finish deleting
+                            // object and buckets before starting next test
+                            setTimeout(() => done(err), 10000);
+                        } else {
+                            done(err);
+                        }
+                    });
                 });
 
                 it(`${test.it}`, done => {
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/test/object/websiteGetWithACL.js]: with no auth credentials sent?

File: tests/functional/aws-node-sdk/test/object/websiteHeadWithACL.js [hunk 9]
```diff
@@ -190,8 +157,23 @@ describe('Head request on bucket website endpoint with ACL', () => {
 
                 it(`${test.it}`, done => {
```
Comment (LaurenSpiegel) [inline tests/functional/aws-node-sdk/test/object/websiteHeadWithACL.js]: with no credentials?

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 10]
```diff
@@ -1,6 +1,206 @@
...
+            secretKey: 'verySecretKey1',
+        };
+    } else if (auth === 'invalidAuth') {
+        authCredentials = {
+            accessKey: 'fakeKey1',
+            secretKey: 'fakeSecretKey1',
+        };
+    } else if (!auth) {
+        authCredentials = undefined;
+    } else {
```
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: only I don't want to throw err if auth is `null` :) only if auth is anything besides `null`, `invalidAuth` or `validAuth`

File: tests/functional/aws-node-sdk/lib/utility/website-util.js (hunk 3 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: basically just asserting there is a `ul` element after the end of the `h3` element (for this error there are two ul elements, one before the `h3` and one after)
the plus 5 doesn't make much difference, it just means create the slice after the `</h3>` -- creating the slice starting from the `indexOf('</h3>')` would create the slice including `</h3>`

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 11]
```diff
@@ -1,6 +1,206 @@
...
+    const { hostname, port, path } = url.parse(urlstring);
+    makeRequest({ hostname, port, method, path, authCredentials }, callback);
+}
+
+function _assertResponseHtml(response, elemtag, content) {
+    if (elemtag === 'ul') {
+        const startIndex = response.indexOf('<ul>');
+        const endIndex = response.indexOf('</ul>');
+        assert(startIndex > -1 && endIndex > -1, 'Did not find ul element');
+        const ulElem = response.slice(startIndex + 4, endIndex);
```
Comment (nicolas2bert) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: _Suggestion_: 
```
const startingTag = '<ul>'
const startingTagLength = startingTag.length
```
So, we understand where this "4" comes from and also if we change the tag we won't need to change its length.

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 12]
```diff
@@ -1,6 +1,206 @@
...
+        _assertResponseHtml(response.body, 'h1', '403 Forbidden');
+        _assertResponseHtml(response.body, 'ul', [
+            'Code: AccessDenied',
+            'Message: Access Denied',
+        ]);
+        if (type === '403-retrieve-error-document') {
+            _assertResponseHtml(response.body, 'h3',
+            'An Error Occurred While Attempting to ' +
+            'Retrieve a Custom Error Document');
+            const startIndex = response.body.indexOf('</h3>') + 5;
```
Comment (nicolas2bert) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: Same suggestion about the length here.

File: tests/functional/aws-node-sdk/lib/utility/website-util.js [hunk 13]
```diff
@@ -1,6 +1,206 @@
...
+
+function _assertContainsHtml(responseBody) {
+    assert(responseBody.startsWith('<html>') &&
+        responseBody.includes('</html>'), 'Did not find html tags');
+}
+
+function _assertResponseHtml404(method, response, type, bucketName) {
+    assert.strictEqual(response.statusCode, 404);
+    if (method === 'HEAD') {
+        if (type !== '404-no-such-bucket'
```
Comment (nicolas2bert) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: Why is this condition only inside the `if (method === 'HEAD')`?
Should not we check it for all the methods?

File: tests/functional/aws-node-sdk/lib/utility/website-util.js (hunk 4 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: the function has been updated with new params and a jsdoc

File: tests/functional/aws-node-sdk/lib/utility/website-util.js (hunk 6 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: this for loop is actually iterating through the header keys and comparing the value of header in result versus expected headers. I updated it to use `.forEach` since the for loop was a bit misleading.

File: tests/functional/aws-node-sdk/lib/utility/website-util.js (hunk 10 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: updated to use your suggestion :)

File: tests/functional/aws-node-sdk/lib/utility/website-util.js (hunk 4 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: I've updated the test helper function to use a `params` object

File: tests/functional/aws-node-sdk/lib/utility/website-util.js (hunk 11 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/lib/utility/website-util.js]: Sure, thank you, I updated it

File: tests/functional/aws-node-sdk/test/object/websiteGet.js (hunk 7 above)
Comment (electrachong) [inline tests/functional/aws-node-sdk/test/object/websiteGet.js]: yes -- think we had a typo before as it was redirecting to `http://google.com//about` (and it was passing the test because google then redirects to `https://www.google.com/about/`)

**Comment by electrachong** [comment]
I guess I never ran an end-to-end but it might not work right now if I try :C
@ironman-machine

**Comment by electrachong** [comment]
@ironman-machine

**Comment by electrachong** [comment]
@ironman-machine

**Comment by electrachong** [comment]
@ironman-machine

**Comment by electrachong** [comment]
@ironman-machine

**Comment by electrachong** [comment]
end-to-end passed, commit were squashed
