### PR TITLE
Data file backend: fix bug for put operation

### LINKED ISSUE #206: Data file backend: bug in put operation
Source file: https://github.com/scality/S3/blob/master/lib/data/file/backend.js#L35

It's possible that stream ends (#L67) before the `fs.write` operation finishes (#L52). Therefore, if `fs.write` fails, there are double return callbacks.

### PR DESCRIPTION
**Pull request by lamphamsy**
Fix #206 
It's possible that stream ends before the `fs.write` operation finishes.
Double checks to make sure that only one callback returns.

### CODE REVIEW

File: lib/data/file/backend.js [hunk 1]
```diff
@@ -65,11 +74,15 @@ export const backend = {
...
             })
             .on('end', () => {
-                log.debug('finished writing data', { key });
-                fs.fsync(fd, () => {
-                    fs.close(fd);
-                    return callback(null, key);
-                });
+                streamEnd = true;
+                // Only in flowing mode when fs.write finished
+                if (request._readableState.flowing) {
```
Comment (LaurenSpiegel) [inline lib/data/file/backend.js]: I don't think we should be relying on the internals of the readable stream to know if our last write is finished.  Instead, why don't we have a variable writeFinished initially set to false and it will only be set to true in the fs.write callback.  So when end is called on the readable stream, we only close the file and call the callback if the writeFinished is set to true.  If it is false, we keep checking back after some interval until it is finished and then close and call the callback.  @GiorgioRegni , does that make sense to you?

Comment (ThibaultRiviere) [inline lib/data/file/backend.js]: By the way why not use the ```finished``` event ?

Comment (LaurenSpiegel) [inline lib/data/file/backend.js]: @ThibaultRiviere, isn't the finish event for a writable stream and the request here is acting as a readable? @RachedBenMustapha, pointed out that with my suggestion if we have more than one chunk being finished up, we could still end early.  He suggests that we push each chunk into an array on each data event and push null into the array when end is called on the readable.  Then in the on.("data") block, we pop off of the end of the array and write it if it is a chunk or close the file and call the callback if the end of the array contains null.

Comment (ThibaultRiviere) [inline lib/data/file/backend.js]: @LaurenSpiegel yes you right and this is why i was thinking about it . I was thinking that the purpose was to wait the ```end``` of the readable stream .
So instead of putting a variable waiting for the end of the readable stream who i think doesn't mean that all datas have been called at the next call of ```on.('data')```.   Even with the ```resume``` witch is asynchronous.
Why not just listen ```finish``` on the writable stream and ```sync``` when all the data have been write ?

Comment (LaurenSpiegel) [inline lib/data/file/backend.js]: As @ThibaultRiviere and I discussed, we are not writing to a writeStream.  We could use fs.createWriteStream instead of just writing to the file and then we would have a stream to pipe to.

Comment (lamphamsy) [inline lib/data/file/backend.js]: @LaurenSpiegel : `fs.createWriteStream ` is cool

**Comment by michael-zapata** [comment]
Since this is a fix, shouldn't this be targeting a release branch first?

**Comment by LaurenSpiegel** [comment]
Since it's a fix only to the file backend, I don't think it is relevant for the release.

File: lib/data/file/backend.js [hunk 2]
```diff
@@ -38,39 +38,16 @@ export const backend = {
...
-                    });
-            })
-            .on('error', err => {
-                log.error('error streaming data from request', { error: err });
-                fs.close(fd);
-                return callback(errors.InternalError);
-            })
-            .on('end', () => {
-                log.debug('finished writing data', { key });
-                fs.fsync(fd, () => {
```
Comment (LaurenSpiegel) [inline lib/data/file/backend.js]: Don't we still want to call fsync?

**Comment by lamphamsy** [comment]
The code is updated

File: lib/data/file/backend.js (hunk 2 above)
Comment (lamphamsy) [inline lib/data/file/backend.js]: It should be used. Thanks

File: lib/data/file/backend.js [hunk 3]
```diff
@@ -37,40 +37,38 @@ export const backend = {
...
-                    fs.close(fd);
-                    return callback(null, key);
+            });
+            request.on('error', err => {
+                log.error('error streaming data from request on read',
+                    { error: err });
+                // close fileStream
+                return fs.close(fd, () => callback(errors.InternalError));
+            }).on('end', () => {
```
Comment (ThibaultRiviere) [inline lib/data/file/backend.js]: The next part should be after the ```finish``` event of the writable stream . 
And i don't understand why not ending the writableStream at the end ?
```js
request.pipe(fileStream).on('error', err => {
    // log your error and all 
}).on('finish', () => {
       fs.fsync(fd, err => {
             if (err) {
                 log.error('error streaming data from request on fsync',
                     { error: err });
                 return callback(errors.InternalError);
             }
             log.debug('finished writing data', { key });
             return fs.close(fd, () => callback(null, key));
        });
});
```

Comment (lamphamsy) [inline lib/data/file/backend.js]: Yes for ending the writableStream
No for `finish` event because at that moment, `fd` is no longer available
