### PR TITLE
README :saving the data or metadata in different locations

### LINKED ISSUE #369: Fails when  saving the data or metadata in different locations
Failing when saving the data or metadata in different locations and specify them. 

```
export S3DATAPATH="/s3/myFavoriteDataPath"
export S3METADATAPATH="/s3/myFavoriteMetadataPath"
npm start
```

### PR DESCRIPTION
**Pull request by nicolas2bert**
Make the Readme.md clearer.
Part: Saving the data or metadata in different locations

### CODE REVIEW

File: lib/metadata/bucketfile/backend.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ import config from '../../Config';
 const errors = arsenal.errors;
 
 const METADATA_PORT = 9990;
-const METADATA_PATH = `${config.filePaths.metadataPath}/`;
+const METADATA_PATH = `${config.filePaths.metadataPath}`;
```
Comment (ThibaultRiviere) [inline lib/metadata/bucketfile/backend.js]: Why remove the ```/``` ?
https://github.com/scality/S3/pull/370/files#diff-b0bf037765b0248b6d3dc6e5356cd087R46
```$METADATA_PATH + $ROOT_DB``` = ```$(pwd)/myFavoriteMetadataPathrootDB``` rigth ?

Comment (nicolas2bert) [inline lib/metadata/bucketfile/backend.js]: Yes sorry, I forgot to change it.

File: README.md [hunk 2]
```diff
@@ -50,12 +50,14 @@ localMetadata directory and the data files will be saved
 in the localData directory within the ./S3 directory on your
 machine.  These directories have been pre-created within the
 repository.  If you would like to save the data or metadata in
-different locations of your choice, you must specify them. So,
-when starting the server:
+different locations of your choice, you must specify them with absolute path.
```
Comment (LaurenSpiegel) [inline README.md]: paths
