### PR TITLE
FIX: Handle `objectPutPart` overwrites

### LINKED ISSUE #153: Refactor objectPutPart API
Metadata is being called twice to get the MPU shadow bucket metadata (once to get the MPU bucket metadata with "services.getMPUBucket" and then again when validating authorization with "services.metadataValidateMultipart").

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Fix #153

Update Utapi metrics on `objectPutPart` overwrites and remove orphaned data on overwrite.

See associated PRs: 
https://github.com/scality/Integration/pull/384
https://github.com/scality/utapi/pull/71

### CODE REVIEW

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart
try

File: lib/api/objectPutPart.js [hunk 1]
```diff
@@ -163,6 +167,39 @@ export default function objectPutPart(authInfo, request, streamingV4Params, log,
...
+                        return next(err);
+                    }
+                    return next(null, res);
+                });
+        },
+        // If there is a pre-existing part, update utapi metrics and delete the
+        // pre-existing part to prevent orphaned data.
+        (res, next) => {
+            if (res) {
+                prevObjectSize = res['content-length'];
```
Comment (electrachong) [inline lib/api/objectPutPart.js]: You can just use a static variable here instead of initializing this to null at the top of the file, right?

Comment (bennettbuchanan) [inline lib/api/objectPutPart.js]: As discussed in-person: `prevObjectSize` is passed later in the callback of `objectPutPart`. It is initialized as `null` at the top of the file to avoid passing the value through other functions in the waterfall. It should also be `null` if there is no pre-existing object because then Utapi will not factor in the value when updating storage utilized. 😺

File: tests/unit/api/multipartUpload.js [hunk 2]
```diff
@@ -1475,6 +1475,74 @@ describe('Multipart Upload API', () => {
...
+                        uploadId,
+                    },
+                };
+                const partRequest = new DummyRequest(requestObj, fullSizedPart);
+                objectPutPart(authInfo, partRequest, undefined, log, err => {
+                    assert.deepStrictEqual(err, null);
+                    next(null, requestObj);
+                });
+            },
+            (requestObj, next) => {
```
Comment (LaurenSpiegel) [inline tests/unit/api/multipartUpload.js]: can you add an assert showing that ds[1] is now there with the first put part?

File: lib/api/objectPutPart.js [hunk 3]
```diff
@@ -163,6 +167,39 @@ export default function objectPutPart(authInfo, request, streamingV4Params, log,
...
+                // Pull locations to clean up any potential orphans in data if
+                // object put is an overwrite of a pre-existing object with the
+                // same key and part number.
+                const oldLocations = Array.isArray(res.partLocations) ?
+                    res.partLocations : [res.partLocations];
+                log.trace('Overwriting MPU part, deleting data');
+                data.batchDelete(oldLocations, logger
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: we should only do the delete after the other part has been successfully stored in data and metadata.

**Comment by bennettbuchanan** [comment]
@ironman-machine
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart

**Comment by bennettbuchanan** [comment]
@ironman-machine after rebase onto master
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart

**Comment by bennettbuchanan** [comment]
@ironman-machine after rebase of Integration
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart

**Comment by bennettbuchanan** [comment]
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart
@ironman-machine try

**Comment by bennettbuchanan** [comment]
end-to-end passed here: http://ci.ironmann.io/gh/scality/Integration/7698

File: lib/api/objectPutPart.js [hunk 4]
```diff
@@ -123,46 +128,47 @@ export default function objectPutPart(authInfo, request, streamingV4Params, log,
...
-        },
+        next => metadata.getObjectMD(mpuBucketName, mpuOverviewKey, log,
+            (err, res) => {
+                if (err && (err.NoSuchBucket || err.NoSuchKey)) {
+                    log.error('error getting the object from mpu bucket', {
+                        error: err,
+                        method: 'objectPutPart::metadata.getObjectMD',
+                    });
+                    return next(errors.NoSuchUpload);
+                }
```
Comment (LaurenSpiegel) [inline lib/api/objectPutPart.js]: you're not handling another error (that is not NoSuchBucket or NoSuchKey)

Comment (bennettbuchanan) [inline lib/api/objectPutPart.js]: Thanks! Updated. 😄

File: tests/unit/api/multipartUpload.js (hunk 2 above)
Comment (bennettbuchanan) [inline tests/unit/api/multipartUpload.js]: Good idea. I have added this assertion.

**Comment by bennettbuchanan** [comment]
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart
@ironman-machine try

File: lib/api/objectPutPart.js (hunk 3 above)
Comment (bennettbuchanan) [inline lib/api/objectPutPart.js]: Updated. https://github.com/scality/S3/pull/472/commits/4cebb2386b96bceea33905bcaa051b06c9d73bb2#diff-c648263eb63c62b8d026c1e437f44551R226

**Comment by bennettbuchanan** [comment]
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart
@ironman-machine try

**Comment by bennettbuchanan** [comment]
Updated: added MetaData `getBucket` call for necessary updates to `splitter`.

**Comment by bennettbuchanan** [comment]
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine please, go

**Comment by bennettbuchanan** [comment]
SCALITY_INTEGRATION_BRANCH=ft/check_utapi_metrics_for_objectPutPart_overwrite
SCALITY_UTAPI_BRANCH=ft/add_metrics_objectPutPart
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine please, go

**Comment by bennettbuchanan** [comment]
E2E passed. Thanks, Jarvis.
